### ISSUE TITLE
マウス軌跡有効で使用すると、Windowがタスクバーに被さる

### ISSUE THREAD

**Issue by namoshika** [creviceapp/creviceapp#17]
v4.15.419 以降でwindowがタスクバーに被さる現象が起きるようです。

Windows 10 Pro 1809を使用中
タスクバーを上表示の場合以外で影響 (上表示は重ならないので無問題)
ジェスチャー定義を以下設定でマウス軌跡描画を無効化すると現象は発生しなくなります

```csharp
Config.GestureStrokeOverlay.Enabled = false;
```
![win_overlaps_with_taskbar](https://user-images.githubusercontent.com/5507106/52521236-695f4780-2cb7-11e9-9fd2-4c5fd130689a.png)

**Comment by rubyu** [comment]
報告ありがとうございます！
こちらの環境でも再現しました。恐らくディスプレイ全面を覆うサイズの透過ウィンドウでジェスチャ軌跡を描写していることに関連した問題だと思います。
調査してみますので今しばらくお待ち下さい。

**Comment by rubyu** [comment]
ひとまず以下の変更を加えてみました。お時間のあるときに検証していただければ幸いです。

### 変更前の仕様
- マウス軌跡はすべてのスクリーンに描写可能

### 変更後の仕様
- マウス軌跡が描写可能なエリアを、ジェスチャが発動したスクリーンのWorkingArea（タスクバーを除いたエリア）に限定

### バイナリ
https://ci.appveyor.com/api/buildjobs/b8ai8gdw01v267gr/artifacts/Crevice.4.16.426.zip

**Comment by namoshika** [comment]
リンク先バイナリで治りました。
マウス軌跡有効状態でもタスクバーが常に前面になります！。
有難うございます！

![19021002](https://user-images.githubusercontent.com/5507106/52532120-10e58400-2d63-11e9-81f7-61878557d3a8.png)

**Comment by rubyu** [comment]
取り急ぎ本件の修正をとりこんだリリースを出しました https://github.com/creviceapp/creviceapp/releases/tag/4.17
