### ISSUE TITLE
If you have multiple Chrome windows (not tabs), the PointedWindow definition will be executed in the ForegroundWindow.

### ISSUE THREAD

**Issue by twinbird827** [creviceapp/creviceapp#22]
ver 4.19.456.0

1.Start chrome and create multiple tabs.
2.Separate the tabs into separate windows.
3.Hover over an inactive chrome window and try to perform the gesture defined in the PointedWindow.
4.The process defined in the active chrome Window is executed.
-> I want the process defined on the inactive chrome Window to be executed.

**Comment by rubyu** [comment]
Hi @twinbird827 , thank you for using crevice!
When there are many windows of the app,  even if you started the gesture on the background one, SendInput will send the message to the foreground window. So, if you want to change the target to PointedWindow, you have to activate it explicitly.

```cs
Do(ctx =>
{
    ctx.PointedWindow.Activate(); // bring the PointedWindow to the top
    SendInput.Multiple().
```

**Comment by twinbird827** [comment]
thank you!
It works as expected.
