### ISSUE TITLE
【不具合報告】Altキーが効いていないかも？

### ISSUE THREAD

**Issue by 8exBCYJi5ATL** [creviceapp/creviceapp#23]
**・環境**
　Crevice 4.19.456.0
　Windows11 Home 21H2

**・確認方法**
　初期状態の `default.csx` の末尾に以下のコードを追加して、
　JoyToKeyのキー設定画面でAltキーが入力されるか確認いたしました。
　⇒ 私の環境では、Altキーは入力されませんでした（AキーやControlキーは入力されました）。
```js
var JoyToKey = When(ctx =>
{
    return (ctx.ForegroundWindow.ModuleName == "JoyToKey.exe");
});

JoyToKey.
On(Keys.RButton).
On(Keys.MoveRight, Keys.MoveLeft, Keys.MoveRight, Keys.MoveLeft).
Do(ctx =>
{
    SendInput.Multiple().
    ExtendedKeyDown(Keys.Alt).
    ExtendedKeyUp(Keys.Alt).
    Send();
});
```

**・本来あるべき挙動**
　Altキーが入力される。

**・実際の挙動**
　Altキーが入力されない。

**・経緯**
　`Shift + Alt + X` というショートカットキーが効いていないことで気が付きました。
　私の環境だけ OR 勘違いかもしれないのですが、念のためご報告させていただきます。

**Comment by rubyu** [comment]
@8exBCYJi5ATL さん
ご報告ありがとうございます！

非常にわかりずらいのですが、Keys.Altはこちらを参照しており、
https://referencesource.microsoft.com/#system.windows.forms/winforms/Managed/System/WinForms/Keys.cs,1427
https://github.com/creviceapp/creviceapp/blob/7204415328521427898e04508cdcab0171ab3840/CreviceApp/US.Keys.cs#L352
キーボードのAltキーを送信する際はVK_MENUやKeys.MenuまたはKeys.LMenu, Keys.RMenuなどを使用してみてください。
https://github.com/creviceapp/creviceapp/blob/7204415328521427898e04508cdcab0171ab3840/CreviceApp/US.Keys.cs#L369

**Comment by 8exBCYJi5ATL** [comment]
@rubyu さん

詳細に教えていただき、ありがとうございます🙇 

なるほど・・・
教えていただいた方法で、やりたいことができました！！
