### ISSUE TITLE
Can I change the "default.csx" folder?

### ISSUE THREAD

**Issue by Hiroto900327** [creviceapp/creviceapp#24]
I use the "Crevice" at work and at home, so I want to save the "default.csx" to the cloud.
Can I change the "default.csx" folder?
Now I copy the "default.csx" to the colud after I change the "default.csx" at work or at home. When I'm at home or at work, I copy the "default.csx" from the colud.

**Comment by rubyu** [comment]
Hi @Hiroto900327, thank you for using Crevice on both work and home!
Can you give it a try to use -s or --script argument when starting the application to specify the script path?
https://creviceapp.github.io/#/?id=comamand-line-interface

Thank you

**Comment by Hiroto900327** [comment]
Hi rubyu, thank you for teaching how to do. I tried this way, and the Crevice4 was started with the cloud "default.csx". But without cmd, the Crevice4 was started with the default "defalut.csx", so I made a .bat file (call crevice4.exe -s "cloud path") for the first time in my life.
Now I use the Crevice4 with the same "default.csx" in the cloud on both work and home!!
Thank you very much!!
